import torch
import argparse
import os
import numpy as np
from sklearn.metrics import roc_auc_score, accuracy_score, f1_score, confusion_matrix, classification_report
from tqdm import tqdm
import csv
from datetime import datetime
from mil_net import Multitask_MILNET, Multitask_MILNET_image_only, Multitask_MILNET_shared_layer
from backbone_builder import BACKBONES
from dataset_loader import BreastDataset
import pandas as pd
from scipy import stats as st
import json

def get_test_args():
    parser = argparse.ArgumentParser(description="Evaluation Script with Optimized Threshold")
    
    # Dataset args
    parser.add_argument("--test_json_path", default="./dataset/json/updated_test-type-0.json")
    parser.add_argument("--data_dir_path", required=True, help="Path to patches")
    parser.add_argument("--clinical_data_path", default="./dataset/clinical_data/preprocessed-type-0.xlsx")  
    parser.add_argument("--preloading", action="store_true")

    # Model args (Must match the trained model settings)
    parser.add_argument("--backbone", choices=BACKBONES, default="vgg16_bn")
    parser.add_argument("--dropout", type=float, default=0.2)
    parser.add_argument("--image_only", action="store_true")
    
    # Checkpoint
    parser.add_argument("--checkpoint_path", type=str, required=True, help="Path to best_combined.pth or best_meta.pth")
    parser.add_argument("--num_workers", type=int, default=8)
    
    # log to csv
    parser.add_argument("--csv_log_path", type=str, default="./evaluation_results.csv", 
                        help="Path to CSV file for logging results (will append if exists)")
    parser.add_argument("--model_name", type=str, default="", 
                        help="model name/identifier for logging")
    # load the model with shared layer
    parser.add_argument("--shared_layer", action="store_true", help="load multi-task model with a shared layer")

    # Threshold options
    parser.add_argument("--threshold_json", type=str, default=None,
                        help="Path to threshold_results.json from quick_threshold.py")
    parser.add_argument("--meta_threshold", type=float, default=0.5,
                        help="Manual threshold for metastasis task (default: 0.5, used if --threshold_json not provided)")
    parser.add_argument("--use_default_threshold", action="store_true",
                        help="Use default 0.5 threshold instead of optimized threshold")

    return parser.parse_args()

def load_optimal_thresholds(threshold_json_path):
    """
    Load optimal thresholds from the JSON file generated by quick_threshold.py
    """
    if not os.path.isfile(threshold_json_path):
        raise FileNotFoundError(f"Threshold JSON file not found: {threshold_json_path}")
    
    with open(threshold_json_path, 'r') as f:
        threshold_data = json.load(f)
    
    meta_threshold = None
    if 'metastasis' in threshold_data:
        meta_threshold = threshold_data['metastasis']['threshold']
        print(f"\n{'='*60}")
        print(f"Loaded Optimal Threshold from: {threshold_json_path}")
        print(f"{'='*60}")
        print(f"Metastasis Threshold: {meta_threshold:.4f}")
        print(f"  - Youden Index: {threshold_data['metastasis']['youden_index']:.4f}")
        print(f"  - Sensitivity: {threshold_data['metastasis']['sensitivity']:.4f}")
        print(f"  - Specificity: {threshold_data['metastasis']['specificity']:.4f}")
        print(f"  - Accuracy: {threshold_data['metastasis']['accuracy']:.4f}")
        print(f"  - F1 Score: {threshold_data['metastasis']['f1_score']:.4f}")
        print(f"{'='*60}\n")
    else:
        raise ValueError("'metastasis' key not found in threshold JSON file")
    
    return meta_threshold

def calculate_extended_metrics(labels, probs, preds):
    """
    Calculates detailed metrics for binary classification.
    Assumes labels are 0 and 1.
    """
    metrics = {}
    
    # Basic Metrics
    metrics['accuracy'] = accuracy_score(labels, preds)
    metrics['auc'] = roc_auc_score(labels, probs)
    metrics['f1'] = f1_score(labels, preds)
    
    # Confusion Matrix (TN, FP, FN, TP)
    tn, fp, fn, tp = confusion_matrix(labels, preds).ravel()
    
    # Extended Clinical Metrics
    # Sensitivity (Recall) = TP / (TP + FN)
    metrics['sensitivity'] = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    metrics['recall'] = metrics['sensitivity'] # Recall is same as Sensitivity
    
    # Specificity = TN / (TN + FP)
    metrics['specificity'] = tn / (tn + fp) if (tn + fp) > 0 else 0.0
    
    # Positive Predictive Value (Precision) = TP / (TP + FP)
    metrics['ppv'] = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    metrics['precision'] = metrics['ppv'] # Precision is same as PPV
    
    # Negative Predictive Value = TN / (TN + FN)
    metrics['npv'] = tn / (tn + fn) if (tn + fn) > 0 else 0.0
    
    # Store confusion matrix components
    metrics['tn'] = int(tn)
    metrics['fp'] = int(fp)
    metrics['fn'] = int(fn)
    metrics['tp'] = int(tp)
    
    return metrics

def log_to_csv(args, meta_metrics, status_acc, status_auc, note, threshold_used):
    """
    Log evaluation results to CSV file (append mode).
    Creates the file with headers if it doesn't exist.
    """
    csv_path = args.csv_log_path
    file_exists = os.path.isfile(csv_path)
    
    # Prepare row data
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    model_identifier = args.model_name if args.model_name else os.path.basename(args.checkpoint_path)
    
    row_data = {
        'timestamp': timestamp,
        'model_name': model_identifier,
        'checkpoint_path': args.checkpoint_path,
        'backbone': args.backbone,
        'image_only': args.image_only,
        'dropout': args.dropout,
        'threshold': threshold_used,
        # Metastasis metrics
        'meta_accuracy': meta_metrics['accuracy'],
        'meta_auc': meta_metrics['auc'],
        'meta_f1': meta_metrics['f1'],
        'meta_sensitivity': meta_metrics['sensitivity'],
        'meta_specificity': meta_metrics['specificity'],
        'meta_ppv': meta_metrics['ppv'],
        'meta_npv': meta_metrics['npv'],
        'meta_tp': meta_metrics['tp'],
        'meta_fp': meta_metrics['fp'],
        'meta_tn': meta_metrics['tn'],
        'meta_fn': meta_metrics['fn'],
        # Status metrics
        'status_accuracy': status_acc,
        'status_auc_macro': status_auc,
        'note': note
    }
    
    # Define column order
    fieldnames = [
        'timestamp', 'model_name', 'checkpoint_path', 'backbone', 'image_only', 'dropout', 
        'threshold', 'meta_accuracy', 'meta_auc', 'meta_f1', 'meta_sensitivity', 'meta_specificity', 
        'meta_ppv', 'meta_npv', 'meta_tp', 'meta_fp', 'meta_tn', 'meta_fn',
        'status_accuracy', 'status_auc_macro', 'note'
    ]
    
    # Write to CSV
    with open(csv_path, 'a', newline='') as csvfile:
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        
        # Write header if file is new
        if not file_exists:
            writer.writeheader()
        
        writer.writerow(row_data)
    
    print(f"\nResults logged to: {csv_path}")
    
def patient_level_metrics(agg_df, meta_threshold):
    """
    Aggregate predictions and labels at patient level.
    """
    status_labels = []
    meta_labels = []
    meta_preds = []
    status_preds = []
    meta_probs = []
    status_probs = []
    
    for p in agg_df['patient_id'].unique():
        patient_row = agg_df[agg_df['patient_id'] == p]
        meta_probs.append(float(np.mean(patient_row['meta_probs'])))
        meta_labels.append(1 if float(np.mean(patient_row['meta_probs'])) > meta_threshold else 0) #int(np.max(patient_row['meta_label']))
        status_labels.append(int(np.max(patient_row['status_label'])))
        # if 1 instance of the patient is positive, then the patient is positive
        meta_preds.append(int(np.max(patient_row['meta_preds'])))
        # Use mode for status predictions
        status_mode = st.mode(patient_row['status_preds'], keepdims=False)
        status_preds.append(int(status_mode.mode))
        
        # For status probs, need to handle multi-class properly
        status_probs.append(np.mean(patient_row['status_probs'].tolist(), axis=0))
    
    # Convert status_probs to numpy array
    status_probs = np.array(status_probs)
    
    return meta_labels, meta_probs, meta_preds, status_labels, status_probs, status_preds

def test(model, dataloader, args, meta_threshold=0.5):
    model.eval()
    
    # Arrays to store results
    meta_preds, meta_labels, meta_probs = [], [], []
    status_preds, status_labels, status_probs = [], [], []
    patient_ids = []
    
    print(f"\nRunning Inference on Test Set...")
    print(f"Using Metastasis Threshold: {meta_threshold:.4f}")
    print("="*60)
    
    with torch.no_grad():
        for data in tqdm(dataloader, ncols=100):
            bag_tensor = data["bag_tensor"].cuda()
            clinical_data = data["clinical_data"].cuda()
            metastasis_label = data["metastasis_label"].cuda()
            status_label = data["status_label"].cuda()
            
            # Forward pass
            if args.image_only:
                meta_logits, status_logits, _ = model(bag_tensor)
            else:
                meta_logits, status_logits, _ = model(bag_tensor, clinical_data)
            
            # Metastasis (Binary) - Apply optimized threshold
            meta_prob = torch.softmax(meta_logits, dim=1)[:, 1] # Probability of class 1
            
            # Apply the optimized threshold instead of argmax
            meta_pred = (meta_prob >= meta_threshold).int()

            meta_probs.extend(meta_prob.cpu().numpy())
            meta_preds.extend(meta_pred.cpu().numpy())
            meta_labels.extend(metastasis_label.cpu().numpy())
            
            # Status (Multiclass) - still use argmax for multiclass
            status_prob = torch.softmax(status_logits, dim=1)
            status_pred = torch.argmax(status_logits, dim=1)
            status_probs.append(status_prob.cpu().numpy())
            status_preds.extend(status_pred.cpu().numpy())
            status_labels.extend(status_label.cpu().numpy())
            patient_ids.extend(data['patient_id'])

    # Convert to numpy
    meta_probs = np.array(meta_probs)
    meta_preds = np.array(meta_preds)
    meta_labels = np.array(meta_labels)
    patient_ids = np.array(patient_ids)
    
    status_probs = np.concatenate(status_probs, axis=0)
    status_preds = np.array(status_preds)
    status_labels = np.array(status_labels)
    
    def log_compute_metrics(meta_labels, meta_probs, meta_preds, status_labels, status_probs, status_preds, note="per bag level"):
        """
        Compute and log metrics for both tasks.
        """
        print(f"\n{note}")
        print("\n" + "="*30)
        print("  METASTASIS (Binary) RESULTS  ")
        print("="*30)
        
        meta_metrics = calculate_extended_metrics(meta_labels, meta_probs, meta_preds)
        
        for k, v in meta_metrics.items():
            if k not in ['tn', 'fp', 'fn', 'tp']:  # Print confusion matrix separately
                print(f"{k.upper():<15}: {v:.4f}")
        
        print(f"\nConfusion Matrix:")
        print(f"  TN: {meta_metrics['tn']:<6} FP: {meta_metrics['fp']}")
        print(f"  FN: {meta_metrics['fn']:<6} TP: {meta_metrics['tp']}")

        print("\n" + "="*30)
        print("  STATUS (Multiclass) RESULTS  ")
        print("="*30)
        
        status_acc = accuracy_score(status_labels, status_preds)
        try:
            status_auc = roc_auc_score(status_labels, status_probs, multi_class='ovr', average='macro')
        except Exception as e:
            print(f"Warning: Could not compute AUC for status task: {e}")
            status_auc = 0.0
            
        print(f"Accuracy       : {status_acc:.4f}")
        print(f"AUC (Macro)    : {status_auc:.4f}")
        print("\nClassification Report:")
        print(classification_report(status_labels, status_preds, digits=4))
        
        return meta_metrics, status_acc, status_auc
        
    # Bag-level metrics
    meta_metrics_bag, status_acc_bag, status_auc_bag = log_compute_metrics(
        meta_labels, meta_probs, meta_preds, 
        status_labels, status_probs, status_preds, 
        note="PER BAG LEVEL"
    )
    
    # Log bag-level results to CSV
    log_to_csv(args, meta_metrics_bag, status_acc_bag, status_auc_bag, 
               note="PER BAG LEVEL", threshold_used=meta_threshold)
    
    # Patient-level aggregation
    agg_dict = {
        'patient_id': patient_ids, 
        'meta_probs': meta_probs,
        'meta_preds': meta_preds,
        'status_preds': status_preds,
        'meta_label': meta_labels,
        'status_label': status_labels,
        'status_probs': list(status_probs)  # Store as list for patient-level aggregation
    }
    agg_df = pd.DataFrame(agg_dict, meta_threshold)
    
    # Get patient-level metrics
    meta_labels_patient, meta_probs_patient, meta_preds_patient, \
    status_labels_patient, status_probs_patient, status_preds_patient = patient_level_metrics(agg_df)
    
    # Patient-level metrics
    meta_metrics_patient, status_acc_patient, status_auc_patient = log_compute_metrics(
        meta_labels_patient, meta_probs_patient, meta_preds_patient, 
        status_labels_patient, status_probs_patient, status_preds_patient, 
        note="PER PATIENT LEVEL"
    )
    
    # log to csv patient-level metrics
    log_to_csv(args, meta_metrics_patient, status_acc_patient, status_auc_patient, 
               note="PER PATIENT LEVEL", threshold_used=meta_threshold)
    

if __name__ == "__main__":
    args = get_test_args()
    
    # Determine which threshold to use
    if args.use_default_threshold:
        meta_threshold = 0.5
        print("\nUsing default threshold: 0.5")
    elif args.threshold_json is not None:
        # Load optimal threshold from JSON
        try:
            meta_threshold = load_optimal_thresholds(args.threshold_json)
        except (FileNotFoundError, ValueError) as e:
            print(f"Error loading threshold from JSON: {e}")
            print(f"Falling back to manual threshold: {args.meta_threshold:.4f}")
            meta_threshold = args.meta_threshold
    else:
        # Use manual threshold
        meta_threshold = args.meta_threshold
        print(f"\nUsing manual threshold: {meta_threshold:.4f}")
    
    test_dataset = BreastDataset(
        args.test_json_path, 
        args.data_dir_path, 
        args.clinical_data_path, 
        is_preloading=args.preloading
    )
    test_loader = torch.utils.data.DataLoader(
        dataset=test_dataset, 
        batch_size=1, 
        shuffle=False, 
        num_workers=args.num_workers
    )
    
    # Initialize Model
    print(f"Initializing model with backbone: {args.backbone}")
    if args.image_only:
        model = Multitask_MILNET_image_only(backbone_name=args.backbone, dropout=args.dropout)
    elif args.shared_layer:
        model = Multitask_MILNET_shared_layer(backbone_name=args.backbone, dropout=args.dropout)
    else:
        model = Multitask_MILNET(backbone_name=args.backbone, dropout=args.dropout)
    
    model = model.cuda()
    
    # Load Checkpoint
    if os.path.isfile(args.checkpoint_path):
        print(f"Loading weights from: {args.checkpoint_path}")
        checkpoint = torch.load(args.checkpoint_path, weights_only=False)
        model.load_state_dict(checkpoint['model_state_dict'])
    else:
        raise FileNotFoundError(f"No checkpoint found at {args.checkpoint_path}")
    
    test(model, test_loader, args, meta_threshold=meta_threshold)
